services:
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile.backend
    ports:
      - "5001:5000"
    volumes:
      - ./api:/usr/src/app/api
    environment:
      FLASK_ENV: development
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: jammin_db
    command: ["flask", "run", "--host=0.0.0.0", "--port=5000"]
    depends_on:
      - mysql  #Start MySQL container before backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/usr/src/app/frontend
      - /usr/src/app/frontend/node_modules
    environment:
      - VITE_BACKEND_URL=http://backend:5000
    depends_on:
      - backend
    command: ["npm", "run", "dev"]

  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: password  
      MYSQL_DATABASE: jammin_db
    ports:
      - "3307:3306"  #Expose MySQL port (Swapped to 3307 to make unique connection, 3306 is MySQL base connection)
    volumes:
      - mysql_data:/var/lib/mysql  #Persist data if container removed
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql #Initialize database on container creation
    networks:
      - default

volumes:
  mysql_data:
